blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://chat.vitejs.dev
    about: 'Ask questions and discuss with other users in real time in the #rails channel'
  - name: Questions & Discussions
    url: https://github.com/ElMassimo/vite_rails/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
